services:
    mongo:
      image: mongo
      ports:
        - 27017:27017
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example
        MONGO_INITDB_DATABASE: phonebook

      volumes: 
        - ./models/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
        - mongo_data_phonebook_dev:/data/db
      container_name: mongo

    server:
      image: phonebook-backend-dev
      build:
        context: .
        dockerfile: dev.Dockerfile
      volumes:
        - ./:/usr/src/app
      ports:
        - 3000:3000
      environment: 
        - MONGODB_URI=mongodb://the_username:the_password@mongo:27017/phonebook
      container_name: phonebook-backend-dev
      depends_on:
        - mongo

volumes:
  mongo_data_phonebook_dev: